# Generated by Django 3.2.3 on 2021-08-03 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='id_number',
        ),
    ]
