# Generated by Django 3.2.3 on 2021-08-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='logo',
            field=models.ImageField(default='/image/none.png', upload_to='', verbose_name='party_logo'),
        ),
    ]
