# Generated by Django 3.2.3 on 2021-08-15 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0004_registeredvoter_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='party',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='votes.party'),
            preserve_default=False,
        ),
    ]
